# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task -a
    silent: true
    desc: Lists the available tasks

  clean:
    desc: Clean up
    cmds:
      - rm -f wordle

  test:
    desc: Run the tests
    cmds:
      - go test -v
      
  tidy:
    desc: Tidy up the modules
    cmds:
      - go mod tidy

  run:
    desc: Run the app
    cmds:
      - go run .

  upgrade-list:
    desc: List available upgrades
    cmds:
      - go list -u -m all

  upgrade-perform:
    desc: Perform upgrade of dependencies
    cmds:
      - go get -u ./...
      - go get -t -u ./...
